package stricken.event;

public enum Event implements IEvent {
	END_OF_TURN, SHOW_COMBAT_ACTION_MENU, POP_IN_GAME_MENU, CRITTER_ACTION, PUSH_IN_GAME_SUBMENU, SHOW_MAIN_MENU, RETURN_TO_GAME, SHOW_SYSTEM_MENU, CRITTER_DEATH, START_GAME, EXIT, LOSE_CONDITION, WIN_CONDITION, CRITTER_SPAWN
}